---
- hosts: all

  vars:
    applications:      
      - firefox
      - google-chrome      
      - mou      
      - robomongo
      - sequel-pro
      - spotify      
      - tunnelblick  
      - sublime-text    
      - iterm2
      - dropbox
      - slack
    application_dir: /Users/matthew/Applications
    brews:
      - docker
      - zsh
      - tig
    caskroom_dir: /opt/homebrew-cask/Caskroom/
    email: EMAIL
    github_username: matthewrennie
    home_dir: /Users/matthew
    name: Matthew Rennie
    zsh_path: /usr/local/bin/zsh

  tasks:
    - include: tasks/homebrew.yml tags=homebrew
    # - include: tasks/zsh.yml tags=zsh

# alias ll='ls -lG' (put it in .bashrc)